### ISSUE TITLE
Can't easily install from the repo

### ISSUE THREAD

**Issue by ForgottenUmbrella** [ele-ala-ele/pixiv_ugoira_gif#2]
This isn't really an issue exactly, more of a request really. 
In order to support one-click installing through Greasemonkey and Tampermonkey, the userscript's file name needs to end in .user.js, not just .js. It'd be nice if you could rename the file as to allow for this ease of installation.

**Comment by ele-ala-ele** [comment]
Hi! I just changed the file name as you suggested. Thanks for the feedback. However I have to tell you I will not continue giving support or updates to this script. I would like to suggest you to use the following chrome extension if this script stops working or presents any issue: 
https://chrome.google.com/webstore/detail/pixiv-ugoira-webm/gbloepphddjkabijnjhaplhhamkmkmik
Regards.
